### ISSUE TITLE
Remover replicação de código na classe `Programa`

### ISSUE THREAD

**Issue by caburu** [ufla-ppoo/RedeSocial#1]
Há dois métodos na classe `Programa` que pedem o autor da mensagem. Essa parte deveria ser tratada em um método separado, evitando a replicação de código.

**Comment by lucasnves** [comment]
Olá @caburu, tudo bem? Tenho interesse em trabalhar nessa issue, posso?

**Comment by caburu** [comment]
Olá @lucasnves, bom dia, tudo joia e você?

Claro, bacana que esteja disposto a colaborar!

Como é um projeto bem simples, não há um procedimento formal para contribuições. Mas, para mantermos as coisas organizadas, seria bom que enviasse a solução da issue na forma de um Pull Request para que eu possa comentar/avaliar a solução.

Qualquer dúvida quanto ao projeto ou à issue em si, estou à disposição.
